language: node_js
node_js:
  - "8"
  - "6"
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - g++-4.8
      - mongodb-org-server
      - mongodb-org-shell
services: mongodb
